/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlayerRouteImport } from './routes/player'
import { Route as HelpRouteImport } from './routes/help'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RunEncounterIdRouteImport } from './routes/run.$encounterId'
import { Route as AdventuresAdventureIdRouteImport } from './routes/adventures.$adventureId'

const PlayerRoute = PlayerRouteImport.update({
  id: '/player',
  path: '/player',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunEncounterIdRoute = RunEncounterIdRouteImport.update({
  id: '/run/$encounterId',
  path: '/run/$encounterId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdventuresAdventureIdRoute = AdventuresAdventureIdRouteImport.update({
  id: '/adventures/$adventureId',
  path: '/adventures/$adventureId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/help': typeof HelpRoute
  '/player': typeof PlayerRoute
  '/adventures/$adventureId': typeof AdventuresAdventureIdRoute
  '/run/$encounterId': typeof RunEncounterIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/help': typeof HelpRoute
  '/player': typeof PlayerRoute
  '/adventures/$adventureId': typeof AdventuresAdventureIdRoute
  '/run/$encounterId': typeof RunEncounterIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/help': typeof HelpRoute
  '/player': typeof PlayerRoute
  '/adventures/$adventureId': typeof AdventuresAdventureIdRoute
  '/run/$encounterId': typeof RunEncounterIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/help'
    | '/player'
    | '/adventures/$adventureId'
    | '/run/$encounterId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/help'
    | '/player'
    | '/adventures/$adventureId'
    | '/run/$encounterId'
  id:
    | '__root__'
    | '/'
    | '/help'
    | '/player'
    | '/adventures/$adventureId'
    | '/run/$encounterId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HelpRoute: typeof HelpRoute
  PlayerRoute: typeof PlayerRoute
  AdventuresAdventureIdRoute: typeof AdventuresAdventureIdRoute
  RunEncounterIdRoute: typeof RunEncounterIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/player': {
      id: '/player'
      path: '/player'
      fullPath: '/player'
      preLoaderRoute: typeof PlayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/run/$encounterId': {
      id: '/run/$encounterId'
      path: '/run/$encounterId'
      fullPath: '/run/$encounterId'
      preLoaderRoute: typeof RunEncounterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adventures/$adventureId': {
      id: '/adventures/$adventureId'
      path: '/adventures/$adventureId'
      fullPath: '/adventures/$adventureId'
      preLoaderRoute: typeof AdventuresAdventureIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HelpRoute: HelpRoute,
  PlayerRoute: PlayerRoute,
  AdventuresAdventureIdRoute: AdventuresAdventureIdRoute,
  RunEncounterIdRoute: RunEncounterIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
